---
- name: add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: add the verification key for the package
  sudo: yes
  shell: curl http://www.rabbitmq.com/rabbitmq-signing-key-public.asc | sudo apt-key add -

- name: update repositories
  apt: update_cache=yes

- name: install rabbitmq
  apt: pkg=rabbitmq-server state=installed force=yes

- name: enable rabbitmq plugins
  rabbitmq_plugin: names={{ item }} state=enabled
  with_items: rabbitmq.plugins
  when: rabbitmq.plugins is defined

- name: add user
  rabbitmq_user: user={{ rabbitmq.user }} password={{ rabbitmq.password }} node=rabbit@{{ vagrant_local.vm.hostname }} tags=administrator,{{ rabbitmq.user }} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

- name: restart rabbitmq
  service: name=rabbitmq-server state=reloaded

- name: enable management plugin
  sudo: yes
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_management

- name: wait for management plugin to start
  wait_for: port=15672 delay=2 timeout=10

- name: download management cli
  chdir: /vagrant
  shell: /usr/bin/wget http://localhost:15672/cli/rabbitmqadmin; chmod a+rx rabbitmqadmin
