---
- name: Download the Go tarball
  get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

- name: Extract the Go tarball
  unarchive: src=/usr/local/src/{{ go_tarball }}
             dest=/usr/local
             copy=no

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Add the Go bin directory to the PATH environment variable for all users
  copy: src=go-bin.sh
        dest=/etc/profile.d

- name: Set GOPATH for all users
  copy: src=go-path.sh
        dest=/etc/profile.d

- name: Install ampq messaging protocol
  shell: export GOPATH=/home/vagrant/go; /usr/local/go/bin/go get github.com/streadway/amqp
  args:
    executable: /bin/bash
    chdir: /home/vagrant

