---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
rabbitmq:
    install: '1'
    user: rmq
    password: rmq
    plugins: [rabbitmq_management, rabbitmq_management_agent, rabbitmq_stomp, rabbitmq_web_stomp, rabbitmq_mqtt, rabbitmq_amqp1_0]

